"""create_UserAuth_model

Revision ID: cfb01ca118ee
Revises: 64a8ea35a1cc
Create Date: 2024-12-16 17:42:12.081011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb01ca118ee'
down_revision = '64a8ea35a1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_data', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('public_data')

    # ### end Alembic commands ###
