# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTestseleniumremembermypassword1:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testseleniumremembermypassword1(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1300, 736)
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "Forgot your password?").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "joserracalera2002@gmail.com"
        )
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
