# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDownloadselected1:
    """Prueba que descarga 1 modelo seleccionado"""

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_downloadselected1(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-group-item:nth-child(3) .model-checkbox"
        ).click()
        self.driver.find_element(By.ID, "downloadSelectedButton").click()
        time.sleep(4)


class TestDownloadselected2:
    """Prueba que descarga 2 modelos seleccionados diferentes"""

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_downloadselected2(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 3").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-group-item:nth-child(2) .model-checkbox"
        ).click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-group-item:nth-child(4) .model-checkbox"
        ).click()
        self.driver.find_element(By.ID, "downloadSelectedButton").click()
        time.sleep(4)


class TestDownloadselected0:
    """Prueba que descarga 0 modelos seleccionados"""

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_downloadselected0(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-group-item:nth-child(2) .model-checkbox"
        ).click()
        time.sleep(1)
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-group-item:nth-child(2) .model-checkbox"
        ).click()
        self.driver.find_element(By.ID, "downloadSelectedButton").click()
        alert_text = self.driver.switch_to.alert.text
        time.sleep(4)
        assert alert_text == "No files selected for download."
