# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestTestseleniumadvancedfiltering1:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testseleniumadvancedfiltering1(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1840, 1048)
        self.driver.get("http://127.0.0.1:5000/explore")
        self.driver.find_element(By.ID, "query").click()
        self.driver.find_element(By.ID, "query").send_keys("fff")
        self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "clear-filters").click()
