name: Build and Publish Image in DockerHub

on:
  push:
    branches: 
     - docker
     - develop
     - main

jobs:
  build-and-push:
    name: Build and Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349


      - name: Create .env file
        run: |
          echo "FLASK_APP_NAME=${{ secrets.FLASK_APP_NAME }}" > .env
          echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "MARIADB_HOSTNAME=${{ secrets.MARIADB_HOSTNAME }}" >> .env
          echo "MARIADB_PORT=${{ secrets.MARIADB_PORT }}" >> .env
          echo "MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}" >> .env
          echo "MARIADB_USER=${{ secrets.MARIADB_USER }}" >> .env
          echo "MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }}" >> .env
          echo "MARIADB_ROOT_PASSWORD=${{ secrets.MARIADB_ROOT_PASSWORD }}" >> .env
          echo "WORKING_DIR=${{ secrets.WORKING_DIR }}" >> .env

      - name: Build Docker image with latest tag
        run: |
          docker compose -f docker/docker-compose.dev.yml up -d --build    

      - name: Push Docker image to DockerHub
        run: |
          docker compose -f docker/docker-compose.dev.yml push web