name: Build and Publish Image in DockerHub

on:
  push:
    branches: 
     - docker
     - develop
     - main

jobs:
  build-and-push:
    name: Build and Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Build Docker image with latest tag
        run: |
          docker-compose -f docker/docker-compose.dev.yml up -d --build    

      - name: Push Docker image to DockerHub
        run: |
          docker-compose -f docker/docker-compose.dev.yml push soniiarm/piripi-hub:latest