name: Build and Publish image in DockerHub

on:
  push:
    branches: 
     - docker

jobs:
  build-and-push:
    name: Build and Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Build Docker image with tag
        run: |
          docker build -t piripi-hub:latest -f ./docker/images/Dockerfile.dev .  

      - name: Push Docker image to DockerHub
        run: |
          docker push piripi-hub:latest      

