name: Python Lint and Format

on:
  push:
    branches: ["*"]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get user email from GitHub API
        id: get_user_email
        run: |
          email=$(curl -s https://api.github.com/users/${{ github.actor }} | \
          jq -r .email)

          echo "USER_EMAIL=$email" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Format code with black
        run: |
          black app

      - name: Commit changes
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "${{ github.actor }}"
          git add .
          git diff --cached --quiet || git commit -m "Format code with black"

      - name: Push changes
        env:
          FORMATER: ${{ secrets.FORMATER }}
        run: |
          git remote set-url origin \
            https://github.com/${{ github.repository }}.git

          git push https://x-access-token:${{ secrets.FORMATER }}@github.com/${{
            github.repository }} HEAD:refs/heads/${{ github.ref_name }}
