name: Python Lint and Format

on:
  push:
    branches: [main, develop, workflows]
  pull_request:
    branches: [main, develop]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: |
          flake8 app

      - name: Format code with black
        run: |
          black app

      - name: Commit changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-name"
          git add .
          git diff --cached --quiet || git commit -m "Format code with black"
          git push
